[build]
  publish = "dist"
  command = "npm run build:netlify"
  functions = "netlify/functions"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  n = "esbuild"

# Environment variables for different deploy contexts
[context.production.environment]
  NODE_ENV = "production"
  NETLIFY = "true"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NETLIFY = "true"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NETLIFY = "true"